config/routes.rb
Audrey::Engine.routes.draw do
  resources :topics do
    member do
      get :up_vote, action: 'up_vote'
      get :down_vote, action: 'down_vote'
    end
  end

  root :to => 'topics#index'
  get :index, to: 'topics#index'
end

app/models/audrey/topic.rb
module Audrey
  class Topic < ActiveRecord::Base
    belongs_to :owner, class_name: Audrey.owner_class.to_s
    has_many :votes

    validates_presence_of :topic
    validates_presence_of :content
    validates_presence_of :owner

    scope :order_by_votes, -> { includes(:votes).select('topics.id, sum(votes.value) as vote_score').group('topics.id').order('vote_score desc') }

    def score
      self.votes.sum(:value)
    end

    def vote(user_id, value)
      Vote.create(user_id: user_id, topic_id: self.id, value: value)
    end

  end
end

app/models/audrey/vote.rb
module Audrey
  class Vote < ActiveRecord::Base
    belongs_to :user, class_name: Audrey.owner_class.to_s
    belongs_to :topic

    validates_uniqueness_of :user_id, scope: :topic_id

    validates_presence_of :user
    validates_presence_of :topic
    validates_presence_of :value
  end
end

app/controllers/audrey/application_controller.rb
module Audrey
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/audrey/topics_controller.rb
require_dependency "audrey/application_controller"

module Audrey
  class TopicsController < ApplicationController
    before_filter :authenticate, except: :index

    def index
      @topics = Topic.joins{votes.outer}.select("audrey_topics.*, sum(audrey_votes.value) as vcount").group("audrey_topics.id").order("vcount DESC")
    end

    def new
      @topic = Topic.new
    end

    def create
      params[:owner_id] = current_user.id
      Topic.create!(topic_params)
      redirect_to(root_path)
    end

    def show
      @topic = Topic.find(params[:id])
    end

    def update
      Topic.find_by!(id: params[:id]).update_attributes(topic_params)
    end

    def up_vote
      Topic.find(params[:id]).vote(current_user.id, 1)
      redirect_to(root_path)
    end

    def down_vote
      Topic.find(params[:id]).vote(current_user.id, -1)
      redirect_to(root_path)
    end

    private
    def topic_params
      params.permit(:owner_id, :topic, :content)
    end

    def vote_params
      params.permit(:user, :topic, :value)
    end

    def authenticate
      unless !current_user.nil?
        redirect_to(root_path)
      end
    end
  end
end

app/helpers/audrey/application_helper.rb
module Audrey
  module ApplicationHelper
  end
end

app/helpers/audrey/feedback_helper.rb
module Audrey
  module FeedbackHelper
  end
end

app/helpers/audrey/topics_helper.rb
module Audrey
  module TopicsHelper
  end
end

app/views/audrey/topics/_form.html.erb
<%= form_for([audrey, @topic]) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this foobar from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-12 columns">
      <label>
        Topic:
        <%= text_field_tag(:topic) %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <label>
        Content:
        <%= text_field_tag(:content) %>
      </label>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/audrey/topics/index.html.erb
<% @topics.each do |topic| %>

  <div class="topic-item" id="topic-<%= topic.id %>">
    <div class="row">
      <div class="large-9 columns">
        <span class="header">
          <strong><%= topic.topic %></strong> <em class="subheader"> by <%= topic.owner.name %></em>
        </span>
      </div>

      <div class="large-3 columns button-bar">
        <ul class="button-group radius">
          <li><%= link_to "Upvote", up_vote_topic_path(topic), class: "label button success" %></li>
          <li><%= link_to "Downvote", down_vote_topic_path(topic), class: "label button alert" %></li>
        </ul>
        <span class="score text-right">
          <small> score: <%= topic.score %> </small>
        </span>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <p class="text-justify">
          <%= topic.content %>
        </p>
      </div>
    </div>
  </div>

<% end %>

app/views/audrey/topics/new.html.erb
<%= render 'form' %>

app/views/audrey/topics/update.html.erb
<h1>Topics#update</h1>
<p>Find me in app/views/audrey/topics/update.html.erb</p>

app/views/audrey/topics/vote.html.erb
<h1>Topics#vote</h1>
<p>Find me in app/views/audrey/topics/vote.html.erb</p>

app/views/layouts/audrey/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Audrey</title>
  <%= stylesheet_link_tag    "audrey/application", media: "all" %>
  <%= javascript_include_tag "audrey/application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>

<nav class="breadcrumbs">
  <a href="/">Back Home</a>
  <a href="/feedback">Feedback Topics</a>
  <a href="/feedback/topics/new">New Topics</a>
</nav>

<div class="container audrey-feedback-engine">
<%= yield %>
</div>

</body>
</html>